### PR TITLE
absoluteRiskUpdate + reproducibleSupportData

### PR DESCRIPTION
**Pull request by Jesse-Islam**
During the fitting process, fitsmoothhazard.fit places event column at the end of matrix. Now, predicting new data does the same. These changes can be found between line 157-160 in R/absoluteRisk.R. Reproducible data has been developed for the support dataset. I made a new folder (dataRaw) that houses a copy of the original data. There also exists a script in the package that imputes and cleans the data (supportData.R).

### CODE REVIEW

**Comment by sahirbhatnagar** [comment]
- the `dataRaw` folder should be renamed to `data-raw` (this is consistent with what's in `.Rbuildignore`)
- you need to document the `support` dataset as is done for the others in [data.R](https://github.com/Jesse-Islam/casebase/blob/master/R/data.R)

**Comment by turgeonmaxime** [comment]
What's the license on the data? Are we allowed to add it to our package, and are there conditions for doing so?

**Comment by Jesse-Islam** [comment]
@sahirbhatnagar at the moment my data.R description for each variable is straight from http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/Csupport.html . (aside from a bit of digging in the paper for a better description of a few variables). Would this be considered plagiarism? Or so long as the references are at the bottom we're fine? My variable descriptions are mostly direct copies from the site linked.

@turgeonmaxime http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets . based on paragraph 3 it appears that they're ok with usage but its unclear about sharing their data separately. I can email them to find out?

**Comment by turgeonmaxime** [comment]
Yes, I think a quick email to Frank Harrell to let him know we're thinking of doing this would be nice.

One other thing: why are we using `mice` for imputing the missing values, as opposed to using the method described on the website? I understand that using multiple imputation can be a good idea in general, but we're only using one imputed dataset.

**Comment by sahirbhatnagar** [comment]
@turgeonmaxime The main reason is that I didn't notice that part on the website about imputing missing values. The other reason, is because of how easy it is to use `mice`.

**Comment by Jesse-Islam** [comment]
My reasoning for predictive mean matching was originally for the benefits of multiple imputation. However, fitting 5 different models felt like it would take away from the point of the case study...

All to say that originally it was a better idea than just using their values, but the narrative gets lost if I fit multiple models... Should I change this to their method? There isn't any benefit over using their method, as I'm only using a single dataset. It shouldn't take too long to change.

**Comment by sahirbhatnagar** [comment]
Unless @turgeonmaxime feels strongly about it, I would leave it as is, using `mice`. It's for illustrative purposes only.

**Comment by turgeonmaxime** [comment]
I agree, let's leave it as it is. Thanks for the clarifications.

**Comment by turgeonmaxime** [comment]
Since all the checks have passed, I'll merge this pull-request. We can still continue working on it and address the points above

**Pull request merged**
